spring.main.allow-bean-definition-overriding: true
spring.profiles.active:
#  - test
#  - mongo
  - sql

# SERVER #
server:
  servlet.context-path: /transactions
  port: 8082

# MONGO #
# Download docker image: docker pull mongo
# Run Docker image: docker run -p 27017:27017 --name mongo1 -d mongo
spring.data.mongodb.uri: mongodb://localhost/ws-transaction-service


# MySQL #
# Download docker image: docker pull mysql
# Run Docker image: docker run -p 3306:3306 --name mysql1 -e MYSQL_ROOT_PASSWORD=mypass -d mysql
spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/ws-transaction-service
    username: root
    password: mypass
